name: LAMP-Stack

services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    networks:
      - default
  
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      UPLOAD_LIMIT: 300M
    depends_on:
      - db
    networks:
      - default

networks:
  default:
    driver: bridge